// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybciwxavqkkhpmlfqmwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliY2l3eGF2cWtraHBtbGZxbXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzY0MTksImV4cCI6MjA3NDAxMjQxOX0.tlQ3GoiXp_EMjjb29wjEv7ndG87Bx9FiQAdEz6Wd3eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});